# Generated by Django 3.2.6 on 2021-08-27 10:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chember_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUtilitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_page_text', ckeditor.fields.RichTextField(verbose_name='Home page text BANGLA')),
            ],
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='mail_address',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
