# Generated by Django 3.2.6 on 2021-08-27 10:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chember_app', '0002_auto_20210827_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1500)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Enter Description')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='chember_location',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteutilitie',
            name='google_map_embed_link',
            field=models.CharField(default=1, max_length=99999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='DoctorInfo'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1500, verbose_name='Blog heading')),
                ('image', models.ImageField(upload_to='blogs', verbose_name='Select an image if you want to add one')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Write your blog here')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chember_app.doctorinfo')),
            ],
        ),
    ]
