# Generated by Django 3.2.6 on 2021-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chember_app', '0003_auto_20210827_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(max_length=200, verbose_name='Enter a treatment type name')),
            ],
        ),
    ]
