# Generated by Django 3.2.6 on 2021-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chember_app', '0005_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteutilitie',
            name='google_map_embed_link',
            field=models.URLField(),
        ),
    ]
