# Generated by Django 3.2.6 on 2021-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chember_app', '0006_alter_siteutilitie_google_map_embed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteutilitie',
            name='google_map_embed_link',
            field=models.CharField(max_length=1000),
        ),
    ]
