# Generated by Django 3.2.6 on 2021-08-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chember_app', '0007_alter_siteutilitie_google_map_embed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs', verbose_name='Select an image if you want to add one'),
        ),
    ]
